added form mui...
BelohvostovAlex/mui-form pull request #1
Opened 2022-05-26 13:26 UTC by BelohvostovAlex

2022-05-31 19:25 UTC, igorTT requested changes
Small enhancement

2022-05-31 19:25 UTC, igorTT commented on src/components/Form/Form.jsx
> +  const [open, setOpen] = React.useState(false);
Import useState

2022-05-31 19:25 UTC, igorTT commented on src/components/Form/styles.js
> +};
```javascript
export const styles  = {
  box: {
    ...some styles
  },
  textFiled: {
    ...some styles
  },
  etc...
}
```

2022-05-31 19:25 UTC, igorTT commented on src/components/Form/Form.jsx
> +import { boxStyles, textFieldStyles, typographyStyles } from './styles';
```javascript
 <Typography sx={styles.textFiled}>
            Title:
          </Typography>

```

2022-05-31 19:25 UTC, igorTT commented on src/components/MainButton/styles.js
> +};
```javascript
export const getStyles= ({ width, height, color }) => ({
  root: {
    width: width,
    height: height ? height : 40,
    background: color,
    color: 'white',
    '&:hover': {
      background: color,
    },
    border: '2px solid black',
  },
};
```

2022-05-31 19:25 UTC, igorTT commented on src/components/MainButton/MainButton.jsx
> +export const MainButton = ({ text, color, width, height, onClick }) => {
```javascript
const classes = getStyles({some props})
return <Button onClick={onClick} sx={classes.root}>{text}</Button>
```

2022-06-01 07:57 UTC, BelohvostovAlex commented on src/components/Form/Form.jsx
> +  const [open, setOpen] = React.useState(false);
done

2022-06-01 08:00 UTC, BelohvostovAlex commented on src/components/Form/styles.js
> +};
done

2022-06-01 08:00 UTC, BelohvostovAlex commented on src/components/Form/Form.jsx
> +import { boxStyles, textFieldStyles, typographyStyles } from './styles';
noted, done

2022-06-01 09:38 UTC, BelohvostovAlex commented on src/components/MainButton/styles.js
> +};
noted, changed

2022-06-01 09:38 UTC, BelohvostovAlex commented on src/components/MainButton/MainButton.jsx
> +export const MainButton = ({ text, color, width, height, onClick }) => {
done

2022-06-01 18:55 UTC, igorTT requested changes

2022-06-01 18:55 UTC, igorTT commented on src/components/MainButton/styles.js
> +// };
Delete it

2022-06-01 18:55 UTC, igorTT commented on src/components/MainButton/styles.js
> +export const mergeClasses = (...styles) => {
```javascript
export const mergeClasses = (...styles) => {
  return styles.reduce((acc, curr) => ({ ...acc, ...curr }), {});
};
```

2022-06-02 06:25 UTC, BelohvostovAlex commented on src/components/MainButton/styles.js
> +// };
deleted

2022-06-02 06:25 UTC, BelohvostovAlex commented on src/components/MainButton/styles.js
> +export const mergeClasses = (...styles) => {
changed

2022-06-02 06:49 UTC, igorTT approved these changes

2022-06-02 06:49 UTC, merged